main: com.amansprojects.moonphase.utilities.Main
name: Utilities
load: STARTUP
version: 1.0
author: ninjadev64 (IGN ninjagamer64)
description: MoonPhase Games Utilities Plugin
commands:
  l:
    description: "Return to the lobby / leave your current minigame."
    usage: "/l"
  maintenance:
    description: "Toggle maintenance mode."
    permission: utilities.maintenance.toggle
permissions:
  utilities.maintenance.bypass:
    description: "Bypass maintenance mode."
    default: op
  utilities.maintenance.toggle:
    description: "Toggle maintenance mode."
    default: op